//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var Registration_ttypes = require('./Registration_types');
var StatusReport_ttypes = require('./StatusReport_types');
var VehicleCreation_ttypes = require('./VehicleCreation_types');


var ttypes = module.exports = {};
