FROM node:alpine

RUN apt-get update &&\
    apt-get install -y python-pip bash-completion curl git nano wget make

RUN echo ". /usr/share/bash-completion/bash_completion" >> ~/.bashrc

RUN pip install cqlsh
RUN sed -i "s/^DEFAULT_CQLVER = '[0-9.]*'$/DEFAULT_CQLVER = '3.4.4'/" /usr/local/bin/cqlsh

RUN npm install -g nodemon

WORKDIR /app

COPY ./package.json /app/
RUN npm install

COPY . /app

CMD [ "npm", "start"]
EXPOSE 3005
